// import React from 'react';
// import "./SignupForm.css";

// function CuisineList() {
//   const cuisines = [
//     'Afghan cuisine',
//     'Albanian cuisine',
//     'Algerian cuisine',
//     'American cuisine',
//     'Andorran cuisine',
//     'Angolan cuisine',
//     'Antigua and Barbuda cuisine',
//     'Argentinian cuisine',
//     'Armenian cuisine',
//     'Australian cuisine',
//     'Austrian cuisine',
//     'Azerbaijani cuisine',
//     'Bahamian cuisine',
//     'Bahraini cuisine',
//     'Bangladeshi cuisine',
//     'Barbadian cuisine',
//     'Belarusian cuisine',
//     'Belgian cuisine',
//     'Belizean cuisine',
//     'Beninese cuisine',
//     'Bhutanese cuisine',
//     'Bolivian cuisine',
//     'Bosnian cuisine',
//     'Brazilian cuisine',
//     'British cuisine',
//     'Bruneian cuisine',
//     'Bulgarian cuisine',
//     'Burkinabe cuisine',
//     'Burundian cuisine',
//     'Cambodian cuisine',
//     'Cameroonian cuisine',
//     'Canadian cuisine',
//     'Cape Verdean cuisine',
//     'Central African Republic cuisine',
//     'Chadian cuisine',
//     'Chilean cuisine',
//     'Chinese cuisine',
//     'Colombian cuisine',
//     'Comorian cuisine',
//     'Congolese cuisine',
//     'Costa Rican cuisine',
//     'Croatian cuisine',
//     'Cuban cuisine',
//     'Cypriot cuisine',
//     'Czech cuisine',
//     'Danish cuisine',
//     'Djiboutian cuisine',
//     'Dominican cuisine',
//     'Dutch cuisine',
//     'East Timorese cuisine',
//     'Ecuadorean cuisine',
//     'Egyptian cuisine',
//     'Emirati cuisine',
//     'Equatorial Guinean cuisine',
//     'Eritrean cuisine',
//     'Estonian cuisine',
//     'Ethiopian cuisine',
//     'Fijian cuisine',
//     'Filipino cuisine',
//     'Finnish cuisine',
//     'French cuisine',
//     'Gabonese cuisine',
//     'Gambian cuisine',
//     'Georgian cuisine',
//     'German cuisine',
//     'Ghanaian cuisine',
//     'Greek cuisine',
//     'Grenadian cuisine',
//     'Guatemalan cuisine',
//     'Guinea-Bissauan cuisine',
//     'Guinean cuisine',
//     'Guyanese cuisine',
//     'Haitian cuisine',
//     'Herzegovinian cuisine',
//     'Honduran cuisine',
//     'Hungarian cuisine',
//     'Icelandic cuisine',
//     'Indian cuisine',
//     'Indonesian cuisine',
//     'Iranian cuisine',
//     'Iraqi cuisine',
//     'Irish cuisine',
//     'Israeli cuisine',
//     'Italian cuisine',
//     'Ivorian cuisine',
//     'Jamaican cuisine',
//     'Japanese cuisine',
//     'Jordanian cuisine',
//     'Kazakhstani cuisine',
//     'Kenyan cuisine',
//     'Kittitian cuisine',
//     'Kosovan cuisine',
//     'Kuwaiti cuisine',
//     'Kyrgyz cuisine',
//     'Laotian cuisine',
//     'Latvian cuisine',
//     'Lebanese cuisine',
//     'Lesotho cuisine',
//     'Liberian cuisine',
//     'Libyan cuisine',
//     'Liechtensteiner cuisine',
//     'Lithuanian cuisine',
//     'Luxembourg cuisine',
//     'Macanese cuisine',
//     'Macedonian cuisine',
//     'Malagasy cuisine',
//     'Malawian cuisine',
//     'Malaysian cuisine',
//     'Maldivian cuisine',
//     'Malian cuisine',
//     'Maltese cuisine',
//     'Marshallese cuisine',
//     'Mauritanian cuisine',
//     'Mauritian cuisine',
//     'Mexican cuisine',
//     'Micronesian cuisine',
//     'Moldovan cuisine',
//     'Monacan cuisine',
//     'Mongolian cuisine',
//     'Montenegrin cuisine',
//     'Moroccan cuisine',
//     'Mosotho cuisine',
//     'Motswana cuisine',
//     'Mozambican cuisine',
//     'Namibian cuisine',
//     'Nauruan cuisine',
//     'Nepalese cuisine',
//     'New Zealand cuisine',
//     'Nicaraguan cuisine',
//     'Nigerian cuisine',
//     'Nigerien cuisine',
//     'North Korean cuisine',
//     'North Macedonian cuisine',
//     'Norwegian cuisine',
//     'Omani cuisine',
//     'Pakistani cuisine',
//     'Palauan cuisine',
//     'Panamanian cuisine',
//     'Papua New Guinean cuisine',
//     'Paraguayan cuisine',
//     'Peruvian cuisine',
//     'Polish cuisine',
//     'Portuguese cuisine',
//     'Qatari cuisine',
//     'Romanian cuisine',
//     'Russian cuisine',
//     'Rwandan cuisine',
//     'Saint Lucian cuisine',
//     'Salvadoran cuisine',
//     'Samoan cuisine',
//     'San Marinese cuisine',
//     'Sao Tomean cuisine',
//     'Saudi Arabian cuisine',
//     'Scottish cuisine',
//     'Senegalese cuisine',
//     'Serbian cuisine',
//     'Seychellois cuisine',
//     'Sierra Leonean cuisine',
//     'Singaporean cuisine',
//     'Slovak cuisine',
//     'Slovenian cuisine',
//     'Solomon Islands cuisine',
//     'Somali cuisine',
//     'South African cuisine',
//     'South Korean cuisine',
//     'South Sudanese cuisine',
//     'Spanish cuisine',
//     'Sri Lankan cuisine',
//     'Sudanese cuisine',
//     'Surinamese cuisine',
//     'Swazi cuisine',
//     'Swedish cuisine',
//     'Swiss cuisine',
//     'Syrian cuisine',
//     'Taiwanese cuisine',
//     'Tajik cuisine',
//     'Tanzanian cuisine',
//     'Thai cuisine',
//     'Togolese cuisine',
//     'Tongan cuisine',
//     'Trinidadian and Tobagonian cuisine',
//     'Tunisian cuisine',
//     'Turkish cuisine',
//     'Turkmen cuisine',
//     'Tuvaluan cuisine',
//     'Ugandan cuisine',
//     'Ukrainian cuisine',
//     'Uruguayan cuisine',
//     'Uzbek cuisine',
//     'Vanuatuan cuisine',
//     'Vatican cuisine',
//     'Venezuelan cuisine',
//     'Vietnamese cuisine',
//     'Welsh cuisine',
//     'Yemeni cuisine',
//     'Zambian cuisine',
//     'Zimbabwean cuisine'
//   ];

//   return (
//     <div className='cuisine-wrapper'>
//     <div className='cuisine-list'>
//     List of Cuisines
//       <ul className='list-of-the-cuisines'>
//         {cuisines.map((cuisine, index) => (
//           <li className="cuisines-country"key={index}>{cuisine}</li>
//         ))}
//       </ul>
//     </div>
//     </div>
//   );
// }

// export default CuisineList;
